CONFERENCE_CREATE_NAME = "CONFERENCE_CREATE_NAME"
CONFERENCE_CREATE_DESCRIPTION = "CONFERENCE_CREATE_DESCRIPTION"
CONFERENCE_CREATE_ZIP = "CONFERENCE_CREATE_ZIP"
CONFERENCE_UPDATE_ZIP = "CONFERENCE_UPDATE_ZIP"

# channel
CHANGE_NAME = "CHANGE_NAME"
